### PR TITLE
adding some dubious info about bears

### LINKED ISSUE #1: Add facts about Bears
Create a `bear.txt` with some facts

### PR DESCRIPTION
**Pull request by Lutz031**
fixes #1

### CODE REVIEW

**Comment by Lutz031** [comment]
supposedly solves #1

**Review by sjvrijn — CHANGES_REQUESTED** [review]
Dubious facts are certainly appreciated :)

Can you please spell Germany with a capital letter?

**Comment by Lutz031** [comment]
@sjvrijn I adressed the comment, please doublecheck

**Review by sjvrijn — APPROVED** [review]
Capitalization looks good now, thanks!

**Pull request merged**
