### PR TITLE
added bee facts

### LINKED ISSUE #7: Add facts about honeybees
Create a `honeybee.txt` with some facts

### PR DESCRIPTION
**Pull request by FritzWien150**
please pull my bee facts

Fixes #7

### CODE REVIEW

**Review by sjvrijn — APPROVED** [review]
Thanks for the poem, I'm sure there's some facts hidden in there ;)

**Review by sjvrijn — CHANGES_REQUESTED** [review]
Can you please add some information on the author of the poem?

**Comment by FritzWien150** [comment]
ok i added the author. please merge

**Review by sjvrijn — APPROVED** [review]
Looks good now, thanks for contributing 🐝

**Pull request merged**
